# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43f80ca11f91b1737b8d52bb90f52b1c1bbad4a9e899f139f053c71687bf2f0a32e44bd5508a2ec20fd001ccc0248d599d4899a3c477d7f7d0fae67cecd3f6ba

test:
  secret_key_base: fe787a14f2490468886de035ac9923e022d3350075f00428b6abb4934b40486e57db2841d1ab71a276aa57acfc756def750e1a5dcc909abc39b80ff0a26c9f52

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
